### ISSUE TITLE
UUID and PhoneID randomly created at every start

### ISSUE THREAD

**Issue by anastalaz** [tducasse/go-instabot#1]
Everytime the script starts new UUID and PhoneID are randomly created. This could lead to an account ban. The insta struct should be created ones and then saved using the Export function of the "github.com/ahmdrz/goinsta" package. At the start, the script should check if there is a saved file and if yes load it with the Import function.

**Comment by tducasse** [comment]
Do you know for sure that Instagram is checking the number of devices used by an account? If that's the case, then it's a valid concern and your solution seems good.

**Comment by anastalaz** [comment]
I am not sure. It didn't happen to me yet. I found a package where they discuss this and it got me thinking:
[https://github.com/liamcottle/Instagram-SDK-PHP/issues/32](https://github.com/liamcottle/Instagram-SDK-PHP/issues/32)

**Comment by tducasse** [comment]
Thanks, I will definitely have to look into it!

**Comment by tducasse** [comment]
It's done 😄
