### ISSUE TITLE
Error running...

### ISSUE THREAD

**Issue by kherio** [tducasse/go-instabot#100]
go run instabot.go returns...: 
# command-line-arguments
./instabot.go:14:2: error: reference to undefined name ‘parseOptions’
  parseOptions()
  ^
./instabot.go:16:2: error: reference to undefined name ‘getConfig’
  getConfig()
  ^
./instabot.go:18:2: error: reference to undefined name ‘login’
  login()
  ^
./instabot.go:19:5: error: reference to undefined name ‘unfollow’
  if unfollow {
     ^
./instabot.go:20:11: error: reference to undefined field or method ‘syncFollowers’
   instabot.syncFollowers()
           ^
./instabot.go:21:12: error: reference to undefined name ‘run’
  } else if run {
            ^
./instabot.go:23:11: error: reference to undefined field or method ‘loopTags’
   instabot.loopTags()
           ^
./instabot.go:25:10: error: reference to undefined field or method ‘updateConfig’
  instabot.updateConfig()
          ^

**Comment by tducasse** [comment]
I think you probably need to install go-instabot again with `go get github.com/tducasse/go-instabot` and then run it using `go-instabot -run` as specified in the [docs](https://github.com/tducasse/go-instabot#how-to-run)
