### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by operationairstrike** [tducasse/go-instabot#105]
~/go-instabot $ go run instabot.go -run -noemail -logs
# command-line-arguments
./instabot.go:14:2: undefined: parseOptions
./instabot.go:16:2: undefined: getConfig
./instabot.go:18:2: undefined: login
./instabot.go:19:5: undefined: unfollow
./instabot.go:20:12: instabot.syncFollowers undefined (type MyInstabot has no field or method syncFollowers)
./instabot.go:21:12: undefined: run
./instabot.go:23:12: instabot.loopTags undefined (type MyInstabot has no field or method loopTags)
./instabot.go:25:11: instabot.updateConfig undefined (type MyInstabot has no field or method updateConfig)
~/go-instabot $

Using the recommended run intructions didn't work

**Comment by norbgazo** [comment]
hi
I have the same problem, do you have an answers?
thanks

**Comment by tducasse** [comment]
You should try installing it globally, then run `go-instabot -run` as specified in the readme
