### ISSUE TITLE
Write documentation for inline environment variables

### ISSUE THREAD

**Issue by tducasse** [tducasse/go-instabot#11]
We need to add the documentation related to #10

**Comment by taghaviali34** [comment]
hi i cannot path this and when i run it gives me and error {loged out } what is this pls help me

**Comment by taghaviali34** [comment]
when i run it gives me this error(the account is logged out ) so what is this help me i send you a picture 
![Untitled](https://user-images.githubusercontent.com/34400687/67994009-7b738280-fc58-11e9-8d5b-b0a5f0c9d837.png)

**Comment by tducasse** [comment]
You have to `config.json` file from `dist/` into `config/` and set up your credentials and parameters there, have you done this?

If you have done it and it doesn't work: the script might have created two files, called `session` and `key`. You could try deleting them before you re-run it

**Comment by taghaviali34** [comment]
i send you  this picture what does it mean ?????

![Untitled](https://user-images.githubusercontent.com/34400687/68012558-a208dc00-fc9f-11e9-9467-ea5fc7e3ce82.png)

**Comment by taghaviali34** [comment]
and when i run this script i must  connect to internet or not????pls answer this question thanks

**Comment by tducasse** [comment]
Yes, you have to be connected to the internet to use the script

**Comment by taghaviali34** [comment]
my friend what does it mean ?this picture 
![Untitled](https://user-images.githubusercontent.com/34400687/68067338-b1009480-fd5a-11e9-9a85-d49281b0a987.png)

**Comment by tducasse** [comment]
this means that it is trying to find a file called `config.json` in the folder called `config/`.

**Comment by taghaviali34** [comment]
so i am using the scripts yes?

**Comment by taghaviali34** [comment]
i give that 2 hashtag but it used 1 hashtag why and it shows me this error
![Untitled](https://user-images.githubusercontent.com/34400687/68067659-cb893c80-fd5f-11e9-811d-65e0b67d9d6e.png)

**Comment by tducasse** [comment]
I can't really be sure, but it looks like either a network problem or something on instagram's side.

**Comment by taghaviali34** [comment]
when it says done it mean the liked comented  this user 
![Untitled](https://user-images.githubusercontent.com/34400687/68067989-d0042400-fd64-11e9-83ce-33adbceec8ab.png)

**Comment by tducasse** [comment]
Yes

**Comment by taghaviali34** [comment]
are you sure but it doesnt show or write for like or comment it just check the users and i am thinking it first check all the users and  like and comment from my parameters which is right ?????
