### ISSUE TITLE
Cannot find go-instabot

### ISSUE THREAD

**Issue by mojsho** [tducasse/go-instabot#14]
Although I installed `go-instabot` via `go get`, but I cannot find `go-instabot` command in my system environment as you said in README.md.
I have Ubuntu 18.04.

**Comment by tducasse** [comment]
I think you may not have your gopath bin folder in your path?
Try to follow the steps here: https://golang.org/doc/code.html#GOPATH

**Comment by mojsho** [comment]
@tducasse Thanks bud. The problem solved. I'd not added go's `bin` directory in my `PATH`.

**Comment by tducasse** [comment]
You're welcome!
