### ISSUE TITLE
on startup error

### ISSUE THREAD

**Issue by steam3d** [tducasse/go-instabot#16]
C:\Go\src\github.com\tducasse\go-instabot>go run instabot.go
#command-line-arguments
.\instabot.go:5:2: undefined: parseOptions
.\instabot.go:7:2: undefined: getConfig
.\instabot.go:9:2: undefined: login
.\instabot.go:10:6: undefined: unfollow
.\instabot.go:11:3: undefined: syncFollowers
.\instabot.go:12:13: undefined: run
.\instabot.go:14:3: undefined: loopTags

**Comment by tducasse** [comment]
Hi!
You shouldn't run the program with `go run instabot.go` as `instabot.go` is not the only file.
For a simpler startup, just use `go-instabot run` as specified [in the README](https://github.com/tducasse/go-instabot#how-to-run).

**Comment by steam3d** [comment]
@tducasse Thx. Do you know solution when instagram ask 'accept your login via email or phone number'?

**Comment by tducasse** [comment]
No, I'm sorry, this seems like a double authentication related to Instagram.
