### ISSUE TITLE
Add a Whitelist and Blacklist file ..

### ISSUE THREAD

**Issue by orangebychoice** [tducasse/go-instabot#18]
Create two files that the script checks before doing an action - a whitelist.json and blacklist.json so that you don't refollow people you've unfollowed or unfollow people you still want to follow even if they're not following you back. I could make this if I got a head start in how to pull this off (maybe).  I figure that with the wait time between actions, having it loop through a couple lists each time really wouldn't matter if it slows it down a little?

FYI: This script is EXACTLY what I've been looking for, and was thinking about building .. no eye candy or goofy phone Apps .. just do what it needs to .. I'm new to Go programming, but I'm familiar with several other languages .. thank you for making this!

**Comment by tducasse** [comment]
Hi!
Sorry for not responding earlier, I saw it while I was travelling and forgot about it later.
I don't have a lot of time to maintain the bot these days, but that could be a good addition.

I can't guarantee I'm going to do it, but if someone wants to, feel free to code something and create a PR!

**Comment by orangebychoice** [comment]
No worries!! Thank you!

**Comment by rudbast** [comment]
Hi, I've created a PR for this, please take a look.. :smile: 

Instead of adding separate file, I reused the original config file and update it after each run.

Also currently the saved list is only username strings, is it okay ? because saving the whole `User` object is problematic for reading later on.

Although username is modifiable so it might be outdated after sometime, I think it's more readable than user id ?

**Comment by tducasse** [comment]
Hi,
I think that `username` is fine.
The script is not supposed to be completely bulletproof, so if people change their Instagram handle, there will be some false positives/negatives, but overall I think it's okay enough.

**Comment by tducasse** [comment]
I'm sorry, it's been two years haha
I've just found some time to clean up this repo and merge a few PRs, I'll fix yours and merge this week!

**Comment by tducasse** [comment]
https://github.com/tducasse/go-instabot/commit/d39db3680228482941ff2b37d6acfddf75852176
solved by this commit ^
