### ISSUE TITLE
It doesn't run...

### ISSUE THREAD

**Issue by waltersantz** [tducasse/go-instabot#19]
Too many errors...
After trying to launch it,  typing "go run instabot.go, tge console displays the following errors:

.\instabot.go:5:2: undefined: parseOptions
.\instabot.go:7:2: undefined: getConfig
.\instabot.go:9:2: undefined: login
.\instabot.go:10:6: undefined: unfollow
.\instabot.go:11:3: undefined: syncFollowers
.\instabot.go:12:13: undefined: run
.\instabot.go:14:3: undefined: loopTags

It seems like the instabot.go file needs some extra coding, I don't know...
![goinsta_error](https://user-images.githubusercontent.com/42345695/44301030-8585bb80-a308-11e8-9a58-ce8792963c2b.jpg)

**Comment by tducasse** [comment]
Hey,
Try to follow this:

https://github.com/tducasse/go-instabot/blob/master/README.md#how-to-run

Once the program is installed, everything should run fine!

You are not supposed to run it with `go run`.

**Comment by tducasse** [comment]
I think you may not have your gopath bin folder in your path?
Try to follow the steps here: https://golang.org/doc/code.html#GOPATH

**Comment by jackbillstrom** [comment]
@waltersantz I tried with `go build` before running the application. That does help, but now I encountered another problem, the output when trying to run my bot is : 

`C:\Users\bloc\go\src\github.com\tducasse\go-instabot>go-instabot -run -nomail
2018/08/22 16:43:41 Error reading config file, While parsing config: invalid character 'C' looking for beginning of value
`
