### ISSUE TITLE
Installed Go at then met with this error...

### ISSUE THREAD

**Issue by stuster123** [tducasse/go-instabot#21]
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/tducasse/go-instabot: exec: "git": executable file not found in %PATH%

What am I doing wrong already?!

**Comment by tducasse** [comment]
I think you need to install git on your system, as `go get` uses git to fetch the package

**Comment by stuster123** [comment]
'go-instabot' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tducasse** [comment]
Try to follow the solution exposed in issue #14
