### ISSUE TITLE
How i can use proxy?

### ISSUE THREAD

**Issue by Beilusquit90** [tducasse/go-instabot#24]
can i`m use proxy with go-instabot?
If yes, how i can do that?

**Comment by anastalaz** [comment]
I don't think you can use a proxy with go-instabot. go-instabot uses a frozen version of the goinsta v1 library to connect to instagram which doesn't support for proxies. Current goinsta v2 has support for proxies but I don't know how much of a hassle it would be to upgrade from v1 to v2.

**Comment by Beilusquit90** [comment]
Thanks =)
