### ISSUE TITLE
Follow people following a profile

### ISSUE THREAD

**Issue by wilsontamarozzi** [tducasse/go-instabot#30]
I know that the Instagram API will change due to privacy measures, but would it be possible to implement a way to track people from a certain profile just like it is in hashtags?

Follow your competitors or similar profiles.

**Comment by AlexanderProd** [comment]
I'd be very interested in this feature as well.

**Comment by tducasse** [comment]
It's an interesting idea! I'm only _very loosely_ maintaining this project because of lack of time, so feel free to fork it :)
