### ISSUE TITLE
Speed bot up

### ISSUE THREAD

**Issue by RRolfes** [tducasse/go-instabot#34]
First off, thanks for building this - it is very cool!

Is there a way to speed the bot up? I am using it to find and follow users with +10k followers that posted with a particular hashtag. I attempted to edit `insta.go` but had no luck. The bot works, but it only checks ~3 accounts per minute. Since there are very few accounts with +10k followers, the process is painfully slow. 

Thanks again!

**Comment by tducasse** [comment]
I don't think it can be done, since there's no way to directly send a request to find a user with a certain number of followers. That's why it first gets a new user, then checks the number, then decides to follow or not.

**Comment by RRolfes** [comment]
Thanks for the quick response!

I realize there's no way to directly search for a user with a certain number of followers. However, what I'd like to do speed up how quickly the bot iterates through all the images with a particular hashtag. Is there a way to do this?

**Comment by RRolfes** [comment]
As a matter of fact, it appears that no changes to `insta.go` are reflected in the behavior of the script. I tried adding `log.Println("Test = " + i)` inside of `func goThrough` in `insta.go` and even commented all of `insta.go` out and it still ran the same. However, cahnges to config.json caused a failure. Is there something I need to do to see the changes to `insta.go`? 

(I've never used go before)

**Comment by tducasse** [comment]
You need to recompile the script for it to take effect. Use `go build *.go` after making your changes.

There is a warning about going too fast on [this line](https://github.com/tducasse/go-instabot/blob/a7cf6953fbf093ab168e8944a082eaf98ccca37e/insta.go#L240) though. The rules for bans on Instagram are not entirely clear, so I can only advise you to be careful and try not to spam.

**Comment by RRolfes** [comment]
I ran `go build *.go` from `/go/src/github.com/tducasse/go-instabot` and it created a new file called `insta` but did not change the behavior of the script. Am I doing something wrong?

**Comment by tducasse** [comment]
You probably need to `go install` also?

**Comment by RRolfes** [comment]
Yes - that did it. Thanks so much!

**Comment by tducasse** [comment]
No worries!
