### ISSUE TITLE
Retrying after error: Invalid status code

### ISSUE THREAD

**Issue by letenkov** [tducasse/go-instabot#37]
Retrying after error: Invalid status code {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?rank_token=...\u0026ranked_content=true", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}

**Comment by tducasse** [comment]
This usually happens when you are spamming instagram and they want you to fill in a captcha or something.
I think you might be able to solve it if you log in the actual instagram app and solve the captcha from there.

Or maybe you are just making too many requests?
