### ISSUE TITLE
Can't install Instabot

### ISSUE THREAD

**Issue by OfficialJosh** [tducasse/go-instabot#38]
So I've downloaded and installed Go via the link provided and I've also installed the latest version of Git.

When I try installing instabot through the go get command, this shows up in my command prompt.

```
# cd .; git clone https://github.com/magiconair/properties C:\Users\Josh\go\src\github.com\magiconair\properties
fatal: could not create work tree dir 'C:\Users\Josh\go\src\github.com\magiconair\properties': Permission denied
package github.com/magiconair/properties: exit status 128
```

**Comment by jouhoff** [comment]
How did you install git? Have you tried downloading it as zip to rule this out?

**Comment by alx-xlx** [comment]
ran `go get github.com/tducasse/go-instabot`
got this error

`# github.com/tducasse/go-instabot
go/src/github.com/tducasse/go-instabot/insta.go:194:39: invalid operation: checkedUser[image.User.Username] && noduplicate (mismatched types bool and *bool)
go/src/github.com/tducasse/go-instabot/util.go:76:5: noduplicate redeclared in this block
        previous declaration at go/src/github.com/tducasse/go-instabot/util.go:33:2
go/src/github.com/tducasse/go-instabot/util.go:92:15: cannot use &noduplicate (type **bool) as type *bool in argument to flag.BoolVar`

**Comment by daddyparodz** [comment]
> ran `go get github.com/tducasse/go-instabot`
> got this error
> 
> `# github.com/tducasse/go-instabot go/src/github.com/tducasse/go-instabot/insta.go:194:39: invalid operation: checkedUser[image.User.Username] && noduplicate (mismatched types bool and *bool) go/src/github.com/tducasse/go-instabot/util.go:76:5: noduplicate redeclared in this block previous declaration at go/src/github.com/tducasse/go-instabot/util.go:33:2 go/src/github.com/tducasse/go-instabot/util.go:92:15: cannot use &noduplicate (type **bool) as type *bool in argument to flag.BoolVar`

me too

**Comment by tducasse** [comment]
Just committed a fix, let me know if it works better
