### ISSUE TITLE
Commenting on on image multiple times - How to only comment once

### ISSUE THREAD

**Issue by spikyonur** [tducasse/go-instabot#39]
The script works well , how ever when it comments sometimes comments 4 times on the same image. Is there a way to configure it to comment on any picture just once. 

Thanks

**Comment by tducasse** [comment]
It's not currently possible, sorry!

**Comment by duraki** [comment]
Any fixes for this? Why closing this task? It seems like an issue per se.

**Comment by tducasse** [comment]
There's no fix, because I don't consider it a bug per se, it's just not a feature that's been implemented.

**Comment by tducasse** [comment]
Just figured out that actually the `-noduplicate` option should do exactly what you want, since it avoids looking at the same user twice, it should also prevents commenting on the same picture twice.

**Comment by duraki** [comment]
@tducasse awesome :-) thanks a lot
