### ISSUE TITLE
Get media and users from location

### ISSUE THREAD

**Issue by SweetSoul** [tducasse/go-instabot#4]
I have the ID of the location that we get from -->
https://www.instagram.com/explore/locations/**212988663**/    --> NYC code..

Then what can i do if i want the bot to only search through that location and only this? I have a code in python that i implemented but the project dev doesn't make any updates do the original code... so..

If it helps i post here

**Comment by tducasse** [comment]
Hello!
I'm not sure it's something that should be implemented by the bot. I'm not even sure the library I use, goinsta, allows it.

I'm sorry, but I don't think I'll do this :(
