### ISSUE TITLE
invalid character 'â' ???

### ISSUE THREAD

**Issue by partTime-NeRD** [tducasse/go-instabot#45]
Hello, was able to install and run.
After many attempts, trying to understand what was triggering the problem, I found out that when I modify the config, just by adding my own username and password, I get this error message:

**Error reading config file, While parsing config: invalid character 'â' looking for beginning of value**

Note that there's no 'â' either in my user or pass...
If I try to run with the given user and pass it works, but it logs out. Just adding my values triggers this.

Please advise, thanks

**Comment by tducasse** [comment]
this looks like there's a special character, either in your password or your username. Maybe not â, but something that's interpreted as such because it's using the wrong encoding to read the json? I have no idea, sorry!
