### ISSUE TITLE
Invalid status code

### ISSUE THREAD

**Issue by basti3893** [tducasse/go-instabot#46]
Hey,

I got issues by following someone. Here's a screenshot of the console:

![image](https://user-images.githubusercontent.com/57417556/68248223-ab39d600-001c-11ea-854a-831f5ed09d6a.png)

and these are my limits in the confif-file:

"limits" : {     
        "maxRetry" : 2,

        "like" : {                          
            "min" : 0,                      
            "max" : 10000                   
        },
        "comment" : {                     
            "min" : 100,                  
            "max" : 10000                 
        },
        "follow" : {                        
            "min" : 200,                    
            "max" : 10000                   
        }
    },
    "tags" : {                              
        "travel" : {                           
            "like" : 3,                     
            "comment" : 0,                  
            "follow" : 10                    
        }                         
    },

Thank you!

**Comment by tducasse** [comment]
hmmmm... I think you're not the only one. I would say it's probably due to something that changed on instagram's end...

**Comment by Swetabhsuman8** [comment]
Yes, right. I am also getting the same error. 

Do you think we can solve this?
