### ISSUE TITLE
Following user currently is broken

### ISSUE THREAD

**Issue by pramonow** [tducasse/go-instabot#48]
Now following is broken and giving back invalid http request
Found out that the issue because the current goinsta library is outdated
easiest wayout currently aside from updating it is removing body from the followingUser method http request and making it GET

**Comment by UN5T48L3** [comment]
I am getting ERROR:Invalid status code when the program starts following, would you like to make a pull request?

**Comment by pramonow** [comment]
3rd party library is integrated here so revision change is needed, might need to explore somemore for that though

**Comment by pramonow** [comment]
https://github.com/tducasse/go-instabot/pull/49 PR have been made for now
you can try to get from my branch for now if you need it

**Comment by brise105** [comment]
@pramonow i cloned your branch but still getting invalid status code. any idea how i can get this working again?

**Comment by pramonow** [comment]
which branch are you using?
are you using this one https://github.com/pramonow/go-instabot/tree/update_version
have you run go mod vendor?

**Comment by brise105** [comment]
thank you for the reply @pramonow.

i cloned from your update_version branch and ran ```go mod vendor``` inside of that *dir*.
i then rebuilt the program w/ ```go build``` and then ran it w/  ```go-instabot -run```.

i feel like i'm maybe missing something obvious.

**Comment by pramonow** [comment]
just to make sure, the go mod contains this right?
`module github.com/tducasse/go-instabot

go 1.13

require (
	github.com/ahmdrz/goinsta/v2 v2.4.5-0.20191021103459-79702a8f3eda
	github.com/spf13/viper v1.4.0
)
`
since the code is working fine in my place and invalid status isnt suppossed to happen anymore
below are my current running code on terminal
`2020/01/08 13:40:36 Using config: config/config.json

2020/01/08 13:40:37 Successfully logged in
2020/01/08 13:40:37 Fetching the list of images for #programming

2020/01/08 13:40:40 Checking followers for mosfarafiee - for #programming
2020/01/08 13:40:40 mosfarafiee has 163 followers
2020/01/08 13:40:41 Liking the picture
2020/01/08 13:40:41 Liked
2020/01/08 13:40:41 Following mosfarafiee
2020/01/08 13:40:42 Followed
2020/01/08 13:40:42 mosfarafiee done

2020/01/08 13:41:03 like 1/4 - follow 1/3
2020/01/08 13:41:03 Checking followers for _._error._.404_._ - for #programming
2020/01/08 13:41:03 _._error._.404_._ has 175 followers
2020/01/08 13:41:03 Liking the picture
2020/01/08 13:41:04 Liked
2020/01/08 13:41:04 Following _._error._.404_._
2020/01/08 13:41:05 Followed
2020/01/08 13:41:05 _._error._.404_._ done
`

**Comment by pramonow** [comment]
and just to make sure, when you do git status its in update_version brandh right? not my master branch, since my master branch is not updated yet too

**Comment by UN5T48L3** [comment]
![image](https://user-images.githubusercontent.com/39417235/72226596-f4218400-35a3-11ea-9b6d-37f6f78a63ba.png)
Do you know what is the problem?

**Comment by pramonow** [comment]
ohh, i haven't checked for comment since i only tried follow and liking
but so far following and liking works well, i will check for it again, thanks for report

**Comment by pramonow** [comment]
@UN5T48L3 sadly i havent found any solution yet for the comment, so i will disable it at the moment, i will try to put issue on the goinsta repo to see if i can find anything

**Comment by UN5T48L3** [comment]
> @UN5T48L3 sadly i havent found any solution yet for the comment, so i will disable it at the moment, i will try to put issue on the goinsta repo to see if i can find anything

btw, there is issue with sync flag. it doesnt shows only who doesnt follow but shows everyone who followed.

**Comment by pramonow** [comment]
hmm gotta check for that again then, i guess some issue with it

**Comment by tushar-boston** [comment]
@pramonow Seems like the comment issue is fixed on the Master branch here https://github.com/ahmdrz/goinsta/tree/master.
Could you please update your repo.

**Comment by pramonow** [comment]
yes @tushar-boston i got that notification since about last month, sadly am not able to test due to keep getting auth challenged in my account, hence i am unable to test it since i have no knowledge to bypass it via code atm
but if you do interested you can try my other branch where i tried to debug it and i will do appreciate it if you do inform me whether it works or no https://github.com/pramonow/go-instabot/tree/fix_comment
Cheers!

**Comment by invinciible** [comment]
@pramonow I've opened a PR fixing comment in your repo.

**Comment by tducasse** [comment]
merged
