### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by brookehenderson10** [tducasse/go-instabot#51]
I am a baby coder and I'm not sure I'm doing something wrong, but I'm not sure what I'm missing. 

When I try to run it, it says directory not found. Please have mercy on me!

<img width="573" alt="Screen Shot 2020-05-09 at 5 33 22 PM" src="https://user-images.githubusercontent.com/55712540/81486682-0cd13c00-921c-11ea-9718-8bba0e1ac2fb.png">

**Comment by bilalasd** [comment]
Hey,

I don't have a mac so I'm not completely sure.

First check where your 'go' folder is, it should be at /Users/brookhenderson/go
or you can do 'cd $HOME/go

There should be two folders, bin and src

Then follow the readme instructions on this github to copy the config file and edit it.

You will also have to add the bin directory to you path.
do this 'export PATH="/Users/brookhenderson/go/bin:$PATH"

then try the 'go-instabot' command, if it still doesn't work then you might need to restart the computer for the PATH variable to update.

**Comment by brookehenderson10** [comment]
<img width="1211" alt="Screen Shot 2020-05-26 at 5 52 52 PM" src="https://user-images.githubusercontent.com/55712540/82958275-aa49a100-9f7a-11ea-9b38-74aff7ef0677.png">

Thank you for your help! That worked. It ran and I got this response: selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by tducasse** [comment]
closing because this one's about instapy, not go-instabot
