### ISSUE TITLE
Following is broken

### ISSUE THREAD

**Issue by operador777** [tducasse/go-instabot#56]
Follow is not working anymore?
I get the "Invalid status code" error when following

How i can fix it?

**Comment by dtokarczyk** [comment]
@operador777 look at this pr https://github.com/tducasse/go-instabot/pull/49

I built that and it started working.

**Comment by muharremkackin** [comment]
Today I tried but it happened again. Says "ERROR: Invalid status code" and stop the application

**Comment by tducasse** [comment]
#49 should work
