### ISSUE TITLE
-bash: go-instabot: command not found

### ISSUE THREAD

**Issue by gitgitav** [tducasse/go-instabot#59]
I followed the instruction in setting up (I uses a mac) and when I finished editing the config file it refuses to run
terminal shows: -bash: go-instabot: command not found 
Any idea how to fix it?
![image](https://user-images.githubusercontent.com/70493700/91673016-7b9e1200-eaf7-11ea-987c-9ee878d12506.png)

**Comment by tducasse** [comment]
your go workspace `bin` folder is probably not in the path.
Try to follow the steps here: https://golang.org/doc/code.html#GOPATH
