### ISSUE TITLE
Retrying after error: fail: User not found ()

### ISSUE THREAD

**Issue by the-jojo-jj** [tducasse/go-instabot#61]
2020/09/25 09:30:03 like 18/5000 - comment 18/5000
2020/09/25 09:30:03 Checking followers for newdeeva.id - for #olshopsurabaya
2020/09/25 09:30:03 newdeeva.id has 4184 followers
2020/09/25 09:30:04 Liking the picture
2020/09/25 09:30:05 Liked
2020/09/25 09:30:05 Commented wearing mask when go out kak.
2020/09/25 09:30:05 newdeeva.id done

2020/09/25 09:30:45 Retrying after error: fail: User not found ()
2020/09/25 09:31:25 Retrying after error: fail: User not found ()
2020/09/25 09:32:26 Retrying after error: fail: User not found ()
2020/09/25 09:33:46 Retrying after error: fail: User not found ()
2020/09/25 09:35:26 Retrying after error: fail: User not found ()
2020/09/25 09:37:26 Retrying after error: fail: User not found ()
2020/09/25 09:39:47 Retrying after error: fail: User not found ()
2020/09/25 09:42:27 Retrying after error: fail: User not found ()
2020/09/25 09:45:27 Retrying after error: fail: User not found ()
2020/09/25 09:48:47 Retrying after error: fail: User not found ()

**Comment by jay-menta** [comment]
Same issue here

**Comment by tducasse** [comment]
so this behaviour is actually from this function
```go
// Retries the same function [function], a certain number of times (maxAttempts).
// It is exponential : the 1st time it will be (sleep), the 2nd time, (sleep) x 2, the 3rd time, (sleep) x 3, etc.
// If this function fails to recover after an error, it will send an email to the address in the config file.
func retry(maxAttempts int, sleep time.Duration, function func() error) (err error) {
	for currentAttempt := 0; currentAttempt < maxAttempts; currentAttempt++ {
		err = function()
		if err == nil {
			return
		}
		for i := 0; i <= currentAttempt; i++ {
			time.Sleep(sleep)
		}
		log.Println("Retrying after error:", err)
	}

	send(fmt.Sprintf("The script has stopped due to an unrecoverable error :\n%s", err), false)
	return fmt.Errorf("After %d attempts, last error: %s", maxAttempts, err)
}
```
It retries many times, and waits for a longer time after every attempt, just in the event that it would be a network error or something similar.
You can configure the number of times it retries the same call in the `config.json` file (using the `maxRetry` parameter), but currently the script just stops if it fails too many times in a row.

We don't have a way to solve this right away, so the best solution would be to just run the script again, hoping it doesn't encounter the same type of error!
If it's _really_ critical for you, you could maybe consider writing a fix and a pull request, and I'll review it!
