### ISSUE TITLE
sudently 2020/09/26 17:50:25 Retrying after error: fail: Please wait a few minutes before you try again. ()

### ISSUE THREAD

**Issue by the-jojo-jj** [tducasse/go-instabot#62]
./go-instabot -run
2020/09/26 17:50:00 Using config: config/config.json

2020/09/26 17:50:00 Successfully logged in
2020/09/26 17:50:00 Fetching the list of images for #fashion

2020/09/26 17:50:25 Retrying after error: fail: Please wait a few minutes before you try again. ()

**Comment by tducasse** [comment]
I can't be sure, because it's out of context, but I'd say this is probably due to using the bot too much, i.e. it's probably hitting the rate limits on Instagram's side
