### ISSUE TITLE
Can't log in anymore 

### ISSUE THREAD

**Issue by g-restante** [tducasse/go-instabot#66]
i used the bot for 2 days, i got a notification from ig saying my account was logging in from suspicious devices and i had increased account security (not 2 factor)

```
2020/10/10 12:47:11 Successfully logged in
2020/10/10 12:47:11 Fetching the list of images for #love

2020/10/10 12:47:31 Retrying after error: fail: login_required ()
```

**Comment by tducasse** [comment]
try to remove the file called `goinsta-session`. That's all I've got, unfortunately, I am not affiliated with Instagram, so I don't know what kind of measures they have to prevent you from spamming, but if they are blocking you, there's no way to go around it

**Comment by g-restante** [comment]
> try to remove the file called `goinsta-session`. That's all I've got, unfortunately, I am not affiliated with Instagram, so I don't know what kind of measures they have to prevent you from spamming, but if they are blocking you, there's no way to go around it

clear the `goinsta-session` worked for me. ty
