### ISSUE TITLE
Like, follow and comments are not working.

### ISSUE THREAD

**Issue by Hawksama** [tducasse/go-instabot#68]
Hi,

The script is not working for the last 4 days. The Instagram account is not blocked ( also I've checked with another Instagram account ). The status of each step is successful but on the app, under the likes is nothing new, also for the number of followers. I've changed the IP address but still nothing. Could the script be banned by Instagram?

Even Unfollow is not working:
```
carabus@workstation:~/go/src/github.com/tducasse/go-instabot$ go-instabot-photo -sync
2020/10/17 18:06:00 Using config: config/config-photo.json

2020/10/17 18:06:00 Successfully logged in

243 users are not following you back!
Do you want to review these users ? [yN]y
Unfollow everyone ? [yN]y
2020/10/17 18:31:56 Config file updated
carabus@workstation:~/go/src/github.com/tducasse/go-instabot$ go-instabot-photo -sync
2020/10/17 19:42:16 Using config: config/config-photo.json

2020/10/17 19:42:16 Successfully logged in

234 users are not following you back!
Do you want to review these users ? [yN]N
Not unfollowing.
```

Thank you.

**Comment by tducasse** [comment]
this might be the reason: https://www.instagram.com/developer/
