### ISSUE TITLE
package go-instabot is not in GOROOT (/usr/local/go/src/go-instabot)

### ISSUE THREAD

**Issue by cherriva** [tducasse/go-instabot#69]
Can someone help me pls?
![Captura de pantalla 2021-01-13 a las 11 37 16](https://user-images.githubusercontent.com/75614453/104441242-b5961f00-5593-11eb-9fe9-e9927fb8684f.png)

**Comment by tducasse** [comment]
it looks like you might have misconfigured your `GOROOT`. It should _probably_ be `/usr/local/go`. More info [here](https://www.geeksforgeeks.org/golang-gopath-and-goroot/).
