### ISSUE TITLE
Problem while installing 

### ISSUE THREAD

**Issue by channelblackri** [tducasse/go-instabot#70]
after downloading some packages it says: 

xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.

**Comment by tducasse** [comment]
Mmm I don't know about that, it's not related to this though... Maybe just run the command they are suggesting?
