### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by pavelotakar** [tducasse/go-instabot#71]
Hi, after a few minutes the application will crash.

Error:
Username and Password not accepted. Learn more at
202 5.7.8  https://support.google.com/mail/?p=BadCredentials j12sm23704702wrt.27 - gsmtp

But when I restart the app, its working again, so this is not an error in the password or username.

What I can do to fix it?

**Comment by pavelotakar** [comment]
(I am using only instagram bot, not email)

**Comment by tducasse** [comment]
Can you tell me which command you're running?

If you want to _not_ use emails, you have to pass the `-nomail` option, i.e. ` go-instabot -run -nomail`

**Comment by pavelotakar** [comment]
Hello, thanks, its not crashing with this error now.

But after somme time it will log this:
Config file updated
Process exited with status 0
 State changed from up to crashed

Is it possible to fix it somehow to make it go 24/7?

**Comment by tducasse** [comment]
No sorry that's not the way it works. Just have a look at the config file and add more tags maybe?

**Comment by pavelotakar** [comment]
Okay, thanks.  Unfortunately, I can't add comments to the instagram now, not even manually.
IG bot notices that it wrote a comment, but even if I look it up, there is no comment.

Do you have any experience with this, or will I never be able to add comments again?

**Comment by tducasse** [comment]
Mmm no I don't know anything about this, sorry 🤷‍♂️
