### ISSUE TITLE
-sync does nothing

### ISSUE THREAD

**Issue by handwound** [tducasse/go-instabot#73]
When I try to use the "-sync" option it just says that the config file was updated, nothing else happens:

              C:\Users\bassl\instabot>go-instabot -sync
              2021/04/27 16:01:06 Using config: config/config.json
              
              2021/04/27 16:01:06 Successfully logged in
              2021/04/27 16:01:07 Config file updated
              
              C:\Users\bassl\instabot>

**Comment by tducasse** [comment]
do you actually follow people, and do you have followers?

**Comment by handwound** [comment]
Yes, I follow people and I have followers. But nevermind, I haven’t changed anything bot it works now
