### ISSUE TITLE
How to get Total Comments/Likes of image

### ISSUE THREAD

**Issue by sadiquekp** [tducasse/go-instabot#74]
Hi,
How to get Total Comments/Likes of image?

**Comment by tducasse** [comment]
mmm I'm not sure, I think you might want to have a look at [the library](https://github.com/ahmdrz/goinsta) that my bot uses. This project is more about automating following/liking/commenting pictures according to a tag, but it relies on `go-insta`, which would certainly allow you to get the total comments or likes on a picture.

**Comment by sadiquekp** [comment]
Okay.
