### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by jatinchoudhary** [tducasse/go-instabot#76]
Bot is working great.
Thank You for creating such a cool bot.

#Feature 1
 Would You Please add a new feature to add more thn 1 account in config file. So that if an account gets banned due to excess commenting the script can automatically detect that and can automatically change to other account.
 
 #Feature 2
Can You make the bot to comment on recent Pictures only? When it searches for a tag, both Top and Recent Posts show up but i want to comment on Recent Pictures Only.
Maybe you can add a time limit like the picture must not be older thn 1 minute or 2 minute.

Sorry for Bad English!
 
 
 Thanks Again for the bot.
  Please Let me know if I can Help in any Way.

**Comment by tducasse** [comment]
I don't really work on this anymore, I just maintain it and fix it when it's completely broken!

Happy for someone else to work on these features and implement them though!
