### ISSUE TITLE
Pls help asap

### ISSUE THREAD

**Issue by lilpeepisgodgbc** [tducasse/go-instabot#78]
C:\Users\maria>go-instabot -run
2021/08/06 23:53:36 Error reading config file, open config/config.json: The system cannot find the path specified.

**Comment by lilpeepisgodgbc** [comment]
i solved it.
How do I upload this to some server?

**Comment by tducasse** [comment]
Sorry, I can't help you with that!

**Comment by KlausBelagyi** [comment]
> i solved it. How do I upload this to some server?

@lilpeepisgodgbc 
Having the same issue.
how did you solve it?

**Comment by tducasse** [comment]
@KlausBelagyi this means that there is no config file (`config.json`) in the `./config/` folder

@lilpeepisgodgbc I'm sorry I can't help you with that, it's way outside the scope of this project!
