### ISSUE TITLE
wanted to personalize some  features  but any changes in the code is not getting reflected in "go-instabot -run" log , even if i delete all files other than config , "go-instabot -run" works fine, how can i edit the files? 

### ISSUE THREAD

**Issue by caesarji** [tducasse/go-instabot#81]

**Comment by tducasse** [comment]
In this case, you need to `git clone` the project instead of using `go install`, and manually compile the go program with `go run` in the right folder

**Comment by caesarji** [comment]
this is going to be a really bad question, but I am struggling to figure out how to manually combine the files , when I individually combine the  "instabot.go" and  "insta.go" , following errors come , which seems genuine cause the files are interconnected, which file am i suppose to compile then?😕Please helpp 

C:\Users\siddh\Desktop\New folder\go-instabot-master\go-instabot-master\go-instabot-master>go run instabot.go
# command-line-arguments
.\instabot.go:14:2: undefined: parseOptions
.\instabot.go:16:2: undefined: getConfig
.\instabot.go:18:2: undefined: login
.\instabot.go:19:5: undefined: unfollow
.\instabot.go:20:11: instabot.syncFollowers undefined (type MyInstabot has no field or method syncFollowers)
.\instabot.go:21:12: undefined: run
.\instabot.go:23:11: instabot.loopTags undefined (type MyInstabot has no field or method loopTags)
.\instabot.go:25:10: instabot.updateConfig undefined (type MyInstabot has no field or method updateConfig)

C:\Users\siddh\Desktop\New folder\go-instabot-master\go-instabot-master\go-instabot-master>go run

C:\Users\siddh\Desktop\New folder\go-instabot-master\go-instabot-master\go-instabot-master>go run insta.go
# command-line-arguments
.\insta.go:41:3: undefined: instabot
.\insta.go:52:2: undefined: instabot
.\insta.go:97:18: undefined: MyInstabot
.\insta.go:157:18: undefined: MyInstabot
.\insta.go:174:18: undefined: MyInstabot
.\insta.go:194:18: undefined: MyInstabot
.\insta.go:208:18: undefined: MyInstabot
.\insta.go:234:18: undefined: MyInstabot
.\insta.go:322:18: undefined: MyInstabot
.\insta.go:349:18: undefined: MyInstabo
