### ISSUE TITLE
Error reading Config file

### ISSUE THREAD

**Issue by Kkrakus** [tducasse/go-instabot#84]
Hi got problem when I try lunch go-instabot
Error:
Error reading Config file,open config/config.json: the system cannot find the  patch specified
Can anyone help?

**Comment by tducasse** [comment]
Are you running the script from a folder where you have a folder named `config`, which contains a file named `config.json`?

**Comment by Kkrakus** [comment]
Yes,

**Comment by tducasse** [comment]
I'm sorry, I don't know how to help! Make sure you've followed all the steps in the readme, good luck :)
