### ISSUE TITLE
-sync

### ISSUE THREAD

**Issue by jayhill365** [tducasse/go-instabot#88]
Doesn't seem to be working like it used to, script works but unfollows people that are following me, added people to the whitelist and bot still unfollowed those people as well .
<img width="330" alt="Screen Shot 2022-01-19 at 5 28 43 PM" src="https://user-images.githubusercontent.com/19259608/150245706-0c2aab7b-efb6-440a-8cba-53921bb94433.png">

**Comment by jayhill365** [comment]
<img width="313" alt="Screen Shot 2022-01-19 at 5 29 16 PM" src="https://user-images.githubusercontent.com/19259608/150245766-ffbeeae9-15a3-4af8-be1a-61d5f400f551.png">

**Comment by tducasse** [comment]
mmmm sorry I am not sure what changed, because I haven't made any update in quite a while now; maybe something with the instagram api? not sure!

**Comment by jayhill365** [comment]
Okay thanks @tducasse  im going to try and take a look at Instagrams  api and see if go can fix the issue
