### ISSUE TITLE
help please i get ERROR:fail:

### ISSUE THREAD

**Issue by leonglo** [tducasse/go-instabot#89]
![image](https://user-images.githubusercontent.com/75845683/154040609-29d83499-a99a-4f21-a699-91c5f487c161.png)
when i run `go-instabot -run` i get the error `ERROR:fail:` i don't know why.
i did change the config.json file with my logins

**Comment by tducasse** [comment]
I'm sorry, unfortunately this is not specific enough for me to help... My guess would be that one of these situations is happening: 
- your login info is wrong
- your account is being challenged by a captcha
- the session saved in `./goinsta-session` is not valid anymore, in which case deleting this file could solve it
- you don't have the right to write this session file in the directory where you're running the script

Good luck!

**Comment by leonglo** [comment]
I'm just so dumb.
my password was incorrect. 
thanks for the help
