### ISSUE TITLE
After login, nothing happens and program exit

### ISSUE THREAD

**Issue by DannyGi** [tducasse/go-instabot#9]
I tried your beautiful software today, but sadly I won't get it running.

$ ./go-instabot -run -nomail -logs -sync
2018/06/12 15:50:35 Using config: config/config.json
2018/06/12 15:50:35 A session file exists
2018/06/12 15:50:35 Successfully logged in

and then the program exits.

Any clue?

**Comment by DannyGi** [comment]
Thanks for immediate response.
I'll try it then come back and report :)

**Comment by DannyGi** [comment]
Works fine, thanks.

**Comment by tducasse** [comment]
Great :)
