### ISSUE TITLE
commenting doesnt work properly

### ISSUE THREAD

**Issue by leonglo** [tducasse/go-instabot#90]
Hey,
i don't know why the script says it comments the posts but it actually doesnt
let me show you
![image](https://user-images.githubusercontent.com/75845683/154287164-882aa284-0f8c-4521-a2fa-ab3973a49e2f.png)
here you can see the script running where it says it has commented but on the post there is only the like and not the comment. even after refreshing there is no comment. i did put comments in the script for it to write them

**Comment by tducasse** [comment]
this is probably an issue with the underlying library I use to access Instagram's API - it's happened before. I might have a look when I have some time, no promises!
