### ISSUE TITLE
Please wait a few minutes before you try again. ()

### ISSUE THREAD

**Issue by sty0133** [tducasse/go-instabot#91]
![EF28BF20-8B7D-4465-8F78-E793E0091F02](https://user-images.githubusercontent.com/72016056/157016526-1e55bc7e-f38e-403f-84c6-07b3247d7cbf.jpeg)

How can I fix this one 
anyone?

**Comment by KlausBelagyi** [comment]
same issue here. Any advice?

**Comment by tducasse** [comment]
Try removing `./goinsta-session` and try again

**Comment by Askeo** [comment]
@tducasse have the same problem, deleted session was not working, deleted whole project did config new, its not working :/ 
![image](https://user-images.githubusercontent.com/76817072/162057939-6f5ca4e7-2a54-4eb2-b6e9-5022e541c52e.png)

**Comment by tducasse** [comment]
this looks like it's related to your instagram account, not this project though. I guess you're hitting their rate-limits!

**Comment by Askeo** [comment]
never used the bot because never started :D then i tried now 22 hours later and same error, dont know how i can hit rate-limit :D but its okay, thank you i try a bit, the problem is there are no verbose logs :/
