### ISSUE TITLE
ERROR:fail: Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by ParrotInTheGarden** [tducasse/go-instabot#97]
i am getting this error, i used ``go install https://github.com/ahmdrz/goinsta@latest`` because ``go get`` doesnt work.

and this is my config file https://pastebin.com/ThGQgwHv

**Comment by wisemiro** [comment]
Same issue, we're you able to resolve it?

**Comment by ParrotInTheGarden** [comment]
nope

**Comment by Rayrsn** [comment]
i have the same problem

**Comment by tducasse** [comment]
I have no idea why this is happening, sorry! 😢
